version: "3.6"
services:
  fortune-droid:
    image: joshuapaulallen/fortune-droid:1.0.1
    container_name: 'fortune-droid'
    env_file: ../env/fortune-droid.env
    ports:
      - "8080:8080"
#  fortune-droid-social:
#    image: joshuapaulallen/fortune-droid-social:latest
#    container_name: 'fortune-droid-social'
#    env_file: ../env/fortune-droid-social.env
#    depends_on:
#      - fortune-droid
#    ports:
#      - "8081:8080"
